// A stored rule-backed shift_instance OWNS its (shift_rule_id, shift_date), so the read-time
// recurring rule must not project a second occurrence for that same rule + date.
//
// Two live surfaces still project rules after PR #207 made the manager calendar instance-only:
// the PUBLIC TEAM BOARD and resolveScheduledSpan(). On both, a cancelled or released occurrence was
// dropped by the display/FILLING test and then immediately re-projected by its own active rule —
// so a removal wrote to the database and changed nothing on screen.
//
// Coverage here is deliberately narrow: the generator itself is untouched, and the helper's own
// unit coverage lives in calendarModel.test.mjs. This file proves the two CONSUMERS.
//   • scheduledSpan  — the REAL module, transpiled with its real deps. Revert the fix and
//                      "cancelled → NO span" fails with {hours:8, source:'rule'}: the phantom span.
//   • public board   — a Next server component with DB calls, so the repo's established pattern
//                      applies (see scheduledLayer.test.mjs). NOTE the division of labour, because
//                      it is easy to misread: the behavioural block below replays the board's loop
//                      and therefore proves what suppression MUST PRODUCE, but it would still pass
//                      against an unfixed board — it calls the helper directly. The SOURCE GUARD is
//                      what proves the board actually WIRES it. Verified by reverting page.tsx to
//                      its pre-fix state: the behavioural block stayed green, the source guard went
//                      red. Neither half is sufficient alone; do not delete one as redundant.
//
// Run:  TZ=UTC node src/lib/schedule/ruleProjectionSuppression.test.mjs
import { readFileSync, writeFileSync, mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { pathToFileURL, fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';
import ts from 'typescript';

const dir = mkdtempSync(join(tmpdir(), 'ruleproj-'));
const urlOf = (n) => pathToFileURL(join(dir, n)).href;
const emit = (rel, name, rewrites = {}) => {
  let { outputText } = ts.transpileModule(readFileSync(fileURLToPath(new URL(rel, import.meta.url)), 'utf8'), {
    compilerOptions: { module: ts.ModuleKind.ESNext, target: ts.ScriptTarget.ES2022 },
  });
  for (const [from, to] of Object.entries(rewrites)) outputText = outputText.split(from).join(to);
  writeFileSync(join(dir, name), outputText);
  return urlOf(name);
};

const { generateRecurringShifts } = await import(emit('../employees.ts', 'employees.mjs'));
const { ruleDatesOwnedByInstances } = await import(emit('./calendarModel.ts', 'calendarModel.mjs'));
emit('./timezone.ts', 'timezone.mjs');
emit('./hours.ts', 'hours.mjs', {
  "'@/lib/employees'": `'${urlOf('employees.mjs')}'`, "'./timezone'": `'${urlOf('timezone.mjs')}'`,
});
const { resolveScheduledSpan } = await import(emit('./scheduledSpan.ts', 'scheduledSpan.mjs', {
  "'@/lib/employees'": `'${urlOf('employees.mjs')}'`,
  "'./hours'": `'${urlOf('hours.mjs')}'`,
  "'./calendarModel'": `'${urlOf('calendarModel.mjs')}'`,
}));

let passed = 0;
const check = (n, c, x = '') => { assert.ok(c, `FAIL: ${n} ${x}`); console.log(`  ✓ ${n}${x ? ` — ${x}` : ''}`); passed++; };

// ── fixture ──────────────────────────────────────────────────────────────────
const RULE = {
  id: 'rule-a', user_id: 'owner-1', employee_id: 'emp-1',
  days_of_week: [1, 2, 3, 4, 5], start_time: '06:00', end_time: '14:00',
  start_date: '2026-09-01', active: true, store_id: null, created_at: '2026-08-01T00:00:00Z',
};
const TARGET = '2026-09-11';           // Friday, generated by RULE
const FROM = '2026-09-10', TO = '2026-09-14';
const TODAY = new Date('2026-09-04T12:00:00Z');

// The materialized pattern occurrence RULE spawned for TARGET.
const inst = (status, o = {}) => ({
  id: 'inst-1', employee_id: 'emp-1', shift_date: TARGET,
  starts_at: '2026-09-11T13:00:00.000Z', ends_at: '2026-09-11T21:00:00.000Z',
  status, source: 'pattern', shift_rule_id: 'rule-a', released_at: null, ...o,
});
const RELEASED = inst('released', { employee_id: null, released_at: '2026-09-05T00:00:00Z' });

// ── the public board's own loop, over the REAL helper + REAL generator ───────
function publicBoardDates(instances) {
  const visible = [];
  for (const i of instances) {
    if (!i.employee_id || i.released_at) continue;
    if (i.status !== 'scheduled' && i.status !== 'claimed' && i.status !== 'worked') continue;
    visible.push({ employee_id: i.employee_id, date: i.shift_date });
  }
  const ownedByInstance = ruleDatesOwnedByInstances(instances);
  const takenByInstance = new Set(visible.map((s) => `${s.employee_id}|${s.date}`));
  for (const g of generateRecurringShifts([RULE], [], FROM, TO, ownedByInstance, TODAY)) {
    if (g.skipped) continue;
    if (takenByInstance.has(`${g.employee_id}|${g.date}`)) continue;
    visible.push({ employee_id: g.employee_id, date: g.date });
  }
  return visible.map((v) => v.date).sort();
}
const onTarget = (rows) => rows.filter((d) => d === TARGET).length;

console.log('\nPUBLIC TEAM BOARD');
{
  const scheduled = publicBoardDates([inst('scheduled')]);
  check('scheduled stored occurrence → exactly ONE row on that date (no duplicate projection)', onTarget(scheduled) === 1, `${onTarget(scheduled)}`);
  const claimed = publicBoardDates([inst('claimed')]);
  check('claimed stored occurrence → exactly ONE row', onTarget(claimed) === 1, `${onTarget(claimed)}`);

  const cancelled = publicBoardDates([inst('cancelled')]);
  check('cancelled stored occurrence → ZERO rows on that date', onTarget(cancelled) === 0, `${onTarget(cancelled)}`);
  const released = publicBoardDates([RELEASED]);
  check('released stored occurrence → ZERO rows on that date', onTarget(released) === 0, `${onTarget(released)}`);

  // Neighbours: Thu 09-10 and Mon 09-14 are both generated by the same rule and must be untouched.
  check('neighbouring dates still project (cancelled case)',
    cancelled.includes('2026-09-10') && cancelled.includes('2026-09-14'), cancelled.join(','));
  check('neighbouring dates still project (released case)',
    released.includes('2026-09-10') && released.includes('2026-09-14'), released.join(','));
  // …and a day with NO stored instance anywhere still projects normally.
  const none = publicBoardDates([]);
  check('no stored instances at all → every rule date projects', none.length === 3, none.join(','));
}

console.log('\nSOURCE GUARD — the board must pass the suppression set, not an empty one');
{
  const src = readFileSync(fileURLToPath(new URL('../../app/s/team/[token]/page.tsx', import.meta.url)), 'utf8');
  const call = src.slice(src.indexOf('generateRecurringShifts('));
  const args = call.slice(0, call.indexOf('))') + 1);
  check('the board imports the helper', src.includes('ruleDatesOwnedByInstances'));
  check('the generator call does NOT pass `new Set()`', !args.includes('new Set()'), args.replace(/\s+/g, ' ').slice(0, 90));
  check('it passes the owned-by-instance set', args.includes('ownedByInstance'));
  // Suppression is worthless if the column is never read.
  check('shift_rule_id is selected from shift_instances', /\.select\('id, employee_id[^']*shift_rule_id'\)/.test(src));
  // The set must be derived from the RAW instances, not the post-filter visible list.
  check('the set is built from `instances`, not the filtered `shifts`',
    /ruleDatesOwnedByInstances\(\s*\(instances/.test(src));
}

console.log('\nSCHEDULED SPAN (the real module)');
{
  const span = (instances) => resolveScheduledSpan({
    employeeId: 'emp-1', date: TARGET, instances, rules: [RULE], exceptions: [],
  });

  const live = span([inst('scheduled')]);
  check('scheduled stored occurrence → span from the INSTANCE', live?.source === 'instance', JSON.stringify(live));
  check('cancelled stored occurrence → NO span (rule fallback suppressed)', span([inst('cancelled')]) === null, JSON.stringify(span([inst('cancelled')])));
  check('released stored occurrence → NO span (rule fallback suppressed)', span([RELEASED]) === null, JSON.stringify(span([RELEASED])));

  // THE OVER-CORRECTION GUARD. Suppression must be scoped to (rule, date) — nothing else.
  const noInstance = span([]);
  check('NO stored occurrence → normal rule fallback still works', noInstance?.source === 'rule', JSON.stringify(noInstance));
  const otherDate = resolveScheduledSpan({
    employeeId: 'emp-1', date: '2026-09-10', instances: [inst('cancelled')], rules: [RULE], exceptions: [],
  });
  check('a cancelled occurrence on ANOTHER date does not suppress this one', otherDate?.source === 'rule', JSON.stringify(otherDate));
  const otherRule = span([inst('cancelled', { shift_rule_id: 'rule-z' })]);
  check('a cancelled occurrence from ANOTHER rule does not suppress this one', otherRule?.source === 'rule', JSON.stringify(otherRule));
  // A one-off (no rule behind it) owns nothing, so it cannot suppress a rule projection either.
  const oneOff = span([inst('cancelled', { shift_rule_id: null, source: 'admin_open' })]);
  check('a cancelled ONE-OFF does not suppress the rule projection', oneOff?.source === 'rule', JSON.stringify(oneOff));
}

console.log(`\nALL PASSED (${passed} assertions)\n`);
