export interface ProductVariant {
  id: string;
  name: string;
  sku?: string;
}

export interface Product {
  id: string;
  user_id: string;
  name: string;
  created_at: string;
  variants?: ProductVariant[];
  tiktok_product_id?: string;
  image_url?: string;
  sku?: string;
}

export interface Entry {
  id: string;
  user_id: string;
  product_id: string;
  date: string;
  gmv: number;
  videos_posted: number;
  views: number;
  shipping: number;
  affiliate: number;
  ads: number;
  platform_fee?: number;
  units_sold?: number;
  units?: number;
  variant_id?: string;
  created_at: string;
  updated_at: string;
  source?: 'manual' | 'tiktok';
  product?: Product;
}

export interface EntryCalculations {
  grossRevPerVideo: number;
  cogs: number;
  totalNetProfit: number;
  netProfitPerVideo: number;
  margin: number;
}

export interface DashboardMetrics {
  totalGMV: number;
  totalNetProfit: number;
  avgMargin: number;
  totalVideos: number;
  totalViews: number;
  totalAds: number;
  totalAffiliate: number;
  totalShipping: number;
  totalUnitsSold: number;
  totalUnits: number; // units/quantity sold (distinct from totalUnitsSold, which is order count on the dashboard)
  entryCount: number;
  avgViewsPerVideo: number;
  revenuePerVideo: number;
  profitPerVideo: number;
  roas: number | null;
  topProduct: { name: string; profit: number } | null;
  productProfits: Record<string, { profit: number; gmv: number; unitsSold: number }>;
  returnsCount?: number;
  returnsAmount?: number;
  samplesCount?: number;
  // True when the COGS source failed, so totalNetProfit/avgMargin are too high and must not be
  // rendered as numbers. Set from the stats read failing, the route flagging a truncated COGS
  // read, or recognised revenue resolving zero COGS.
  cogsUnavailable?: boolean;
}

export interface ChartData {
  profitByDate: { labels: string[]; data: number[] };
  gmvByDate: { labels: string[]; data: number[] };
  productCompare: { labels: string[]; gmv: number[]; profit: number[] };
  costBreakdown: { labels: string[]; data: number[]; colors: string[]; rawAmounts: number[] };
  marginByDate: { labels: string[]; data: number[] };
}

export interface FilterState {
  dateFrom: string | null;
  dateTo: string | null;
  productId: string; // 'all' | uuid
}

export type MarginLevel = 'green' | 'yellow' | 'red';

export type EmployeeStatus = 'active' | 'probation' | 'former';

// Suggested roles the UI offers as presets; `role` is stored as free text so other
// values are allowed.
export type EmployeeRole = 'host' | 'fulfillment' | 'manager' | 'support' | 'other';

export interface Employee {
  id: string;
  user_id: string;
  name: string;
  role: string;
  status: EmployeeStatus;
  hourly_rate: number;
  hire_date: string | null;
  probation_end_date: string | null;
  store_id?: string | null;
  phone?: string | null; // migration 085 — contact number for scheduling SMS (Deploy B, Part 6)
  created_at: string;
  updated_at: string;
}

// How a shift row was produced (migration 070). 'manual' = hand-entered in the Shifts UI
// OR materialized from a recurring rule (behaves exactly as before the time clock);
// 'time_clock' = generated by the employee kiosk and gated on manager confirmation in pay.
export type ShiftSource = 'manual' | 'time_clock';

export interface Shift {
  id: string;
  user_id: string;
  employee_id: string;
  date: string;
  start_time: string; // 'HH:MM' or 'HH:MM:SS'
  end_time: string | null; // null = OPEN shift (in progress, not yet ended)
  store_id?: string | null;
  // Set when this row was MATERIALIZED from a recurring rule (migration 055); NULL = a
  // plain one-off shift. FK is ON DELETE SET NULL, so deleting the rule keeps the row.
  source_rule_id?: string | null;
  // Time-clock integration (migration 070). All shift rows carry these (DB defaults:
  // source 'manual', break_minutes 0, confirmed_at NULL) so existing rows are unchanged.
  source: ShiftSource;
  confirmed_at: string | null; // manager confirmation gate — only 'time_clock' shifts are gated in pay
  confirmed_by: string | null; // auth.users id of the manager who confirmed (set server-side with confirmed_at)
  break_minutes: number;       // unpaid break minutes subtracted from derived pay
  // Time-clock REAL SPAN (migration 072). For 'time_clock' shifts these are the authoritative
  // punch instants; pay derives hours from them so a >24h span isn't undercounted by the
  // start_time/end_time midnight wrap. NULL on manual/recurring shifts (use start/end there).
  clock_in_at?: string | null;
  clock_out_at?: string | null;
  auto_closed?: boolean;       // reconciler auto-closed a forgotten/over-long open punch — FLAG for review
  created_at: string;
  updated_at: string;
}

// A recurring-shift RULE. Instances are computed from the rule minus its
// exceptions at read time — never materialized (see migration 047).
export interface ShiftRule {
  id: string;
  user_id: string;
  employee_id: string;
  days_of_week: number[]; // getUTCDay() numbers: 0=Sun … 6=Sat
  start_time: string;
  end_time: string;
  start_date: string;
  active: boolean;
  store_id?: string | null;
  created_at: string;
  updated_at: string;
}

export type ShiftExceptionType = 'skip' | 'modified';

// A per-date override on a rule: 'skip' suppresses that date's instance;
// 'modified' replaces its hours (a null side falls back to the rule's time).
export interface ShiftException {
  id: string;
  user_id: string;
  rule_id: string;
  date: string;
  type: ShiftExceptionType;
  modified_start: string | null;
  modified_end: string | null;
  created_at: string;
  updated_at: string;
}

// ─── Time-clock attendance (migration 070) ──────────────────────────────────
// RAW punch trail behind the kiosk. These are the auditable source of truth and are
// NEVER edited by managers — a manager corrects the derived `shifts` row instead, leaving
// these untouched. All timestamps are server-generated (timestamptz), never client-set.

// Lifecycle of one work session. clocked_out_at IS NULL is the authoritative "active"
// test; `status` is a convenience mirror kept in sync by the RPCs (071).
export type TimeEntryStatus = 'open' | 'on_break' | 'closed';

export interface EmployeeTimeEntry {
  id: string;
  user_id: string;
  employee_id: string;
  store_id?: string | null;
  shift_id: string | null; // the ONE shift produced at clock-out (ON DELETE SET NULL)
  clocked_in_at: string;
  clocked_out_at: string | null;
  status: TimeEntryStatus;
  // migration 072: reconciler set this on an open punch left past the plausible-shift cap (~11h).
  // The entry is NOT auto-closed — it stays open + out of pay until a human clocks it out with the
  // real time (which clears this). A loud "needs manual close" flag, never invented hours.
  needs_manual_close?: boolean;
  created_at: string;
  updated_at: string;
}

export interface EmployeeTimeBreak {
  id: string;
  user_id: string;
  employee_id: string;
  time_entry_id: string;
  started_at: string;
  ended_at: string | null; // null = break in progress
  created_at: string;
  updated_at: string;
}

// ─── Scheduling v1 (migrations 085, 086) ────────────────────────────────────
// The two pay-role classes. employees.role is free text, but scheduling treats these two.
export type ScheduleRole = 'host' | 'fulfillment';

// A materialized, dated occurrence of ONE person's recurring shift_rule. Written FORWARD
// (shift_date > today) by the forward materializer; NEVER by the payroll past-materializer,
// and never read by payroll (isPayableShift/shifts stay the pay path). shift_rule_id links back
// to the rule that spawned it (migration 086; ON DELETE SET NULL — the instance outlives its rule).
export type ShiftInstanceStatus =
  | 'scheduled'
  | 'released'
  | 'claimed'
  | 'worked'
  | 'missed'
  | 'cancelled';
export type ShiftInstanceSource = 'pattern' | 'claim' | 'admin_open';

export interface ShiftInstance {
  id: string;
  user_id: string;
  shift_rule_id: string | null; // rule that spawned it (migration 086); null once the rule is deleted
  employee_id: string | null; // NULL while unclaimed after release
  store_id?: string | null;
  // migration 090 — admin one-time shifts. role is set on admin_open rows (pattern/claim derive it
  // from the employee); note is optional free text. NULL on pattern/claim.
  role?: string | null;
  note?: string | null;
  shift_date: string; // 'YYYY-MM-DD' (LA-local calendar date)
  starts_at: string; // timestamptz — computed in America/Los_Angeles
  ends_at: string; // timestamptz
  status: ShiftInstanceStatus;
  source: ShiftInstanceSource;
  released_at: string | null;
  released_by: string | null; // employees.id of the releaser
  excused: boolean;
  excused_by: string | null; // auth.users id (manager action)
  excused_note: string | null;
  created_at: string;
}

export type ShiftClaimStatus = 'auto_approved' | 'pending' | 'approved' | 'rejected';

export interface ShiftClaim {
  id: string;
  user_id: string;
  shift_instance_id: string;
  claimed_by: string; // employees.id
  claimed_at: string;
  status: ShiftClaimStatus;
  projected_week_hours: number | null; // snapshot at claim time
  approved_by: string | null; // auth.users id (manager action)
  approved_at: string | null;
}

export interface EmployeeAccessToken {
  id: string;
  user_id: string;
  employee_id: string;
  token: string; // 32 random bytes, base64url — generated in app code
  active: boolean;
  created_at: string;
  revoked_at: string | null;
}

// Append-only trail; drop counts are DERIVED from it per pay period (no stored ledger).
// shift_date is denormalized so the row is self-sufficient after its instance is deleted
// (shift_instance_id is ON DELETE SET NULL). The guard/drops key on (employee_id, shift_date)
// (migration 086). pay_period_start is the period containing the event's action time (created_at)
// — see payPeriodStartFor.
export type AttendanceEventType = 'released' | 'claimed' | 'missed_unfilled' | 'excused';

export interface AttendanceEvent {
  id: string;
  user_id: string;
  employee_id: string;
  shift_instance_id: string | null;
  shift_date: string;
  event_type: AttendanceEventType;
  pay_period_start: string; // 'YYYY-MM-DD' Monday
  created_at: string;
}
